name: On Merge Main

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  pages: write
  contents: write
  issues: write
  pull-requests: write

jobs:
  on_main_merge:
    name: Run On Merge Main Workflow
    uses: p2arthur/shared-config-fork/.github/workflows/on-merge-main.yml@main
    with:
      project-type: node
      node-version: "22"
      python-version: "3.12"
      working-directory: .
      skip-docs: false
    secrets:
      BOT_ID: ${{ secrets.BOT_ID }}
      BOT_SK: ${{ secrets.BOT_SK }}
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
