name: On Merge Main

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  pages: write
  contents: write
  issues: write
  pull-requests: write

jobs:
  on_main_merge:
    name: Run On Merge Main Workflow
    uses: p2arthur/merged-config/.github/workflows/on-merge-main.yml@main
    with:
      project-type: node # use node or python
      # publish-docs: true         # optional, defaults true
      # publish-devportal: false   # optional
    secrets:
      BOT_ID: ${{ secrets.BOT_ID }}
      BOT_SK: ${{ secrets.BOT_SK }}
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }} # if needed for installs/publish

